### PR TITLE
Push history

### PR DESCRIPTION
**Pull request by tommyent**
Not sure if you are interested but I branched it so I could add some quick and dirty styles to the push history. It's going to need some tweaking for sure since I don't have a variety of notifications to test it with. Most of mine are one line.

Not trying to step on Kevin's work I just wanted something until then. Or if he doesn't have time I can work on something more permanent.

### CODE REVIEW

**Comment by joaomgcd** [comment]
Thank you very much! 

However some types of pushes look off.

Try using a push like 

https://joinjoaomgcd.appspot.com/_ah/api/messaging/v1/sendPush?text=Hello&title=This%20is%20a%20title&icon=https%3A%2F%2Fdl.dropboxusercontent.com%2Fu%2F9787157%2Fxbox.png&url=http%3A%2F%2Fwww.androidpolice.com%2F&clipboard=this%20is%20the%20clipboard&file=http%3A%2F%2Fwallpapercave.com%2Fwp%2F5ynt7Gb.jpg&deviceId=YOUR_DEVICE_ID and check some issues:

- Title is not bolder then text and is same size
- Icon is too large
- the whole "push card" should have the hand icon because it has an url associated to it

I can do these fixes later if you want :) But if you have time to do them it would be great!

Thakns again for your help!

**Comment by tommyent** [comment]
Yeah I knew it would still need work. I can do it at some point today. I don't have a huge variety in my pushes. Here's what I was working with :)
screenshot 2016-10-13 08 23 00
So this will be good
Right now I have this 
screenshot 2016-10-13 08 22 24

Was it meant to have a file, clipboard, title (&link) and icon all in one notification? Or Should it be 3 notifications. File, clipboard and the one with the title link, text and icon?
I'm only using Android and Chrome but I'm trying to figure a way a push like that could be created.

**Comment by tommyent** [comment]
@joaomgcd oh and you see the last push at 8:08 AM that was a post from Google+. For some reason any push from Google+ shows up empty.

**Comment by joaomgcd** [comment]
Yeah, that push was supposed to have those all in just one push, just so you can test it out. :) In a real situation a push like that probably wouldn't occur but it can occur using the API if someone wants to.

About the pushes with nothing in them, yeah, I need to look at them later. Probably some kind of data that I didn't account for.

Thanks again!

**Comment by tommyent** [comment]
So another small problem. This was a link from Chrome.
`      "deviceId": "",
      "files": [],
      "find": false,
      "fromTasker": false,
      "id": "",
      "location": false,
      "senderId": "",
      "text": "Google Assistant commands that work right now [VIDEO]",
      "toTasker": false,
      "url": "http://phandroid.com/2016/10/11/google-assistant-google-allo-video/",
      "date": 1476362120936
    },`
Ideally "text" in this case would be "title" since it's all that displays in the card. This is why I had the .clickable #text rule before. Is this easy enough to fix in the App?

**Comment by joaomgcd** [comment]
What do you mean exactly by "fix in the App"? Can you  clarify? thanks!

**Comment by tommyent** [comment]
Not fix but be more specific in the JSON file. 

Right now links are "text" instead of "title". It would be ideal if they to have them be titles since they are not accompanied by text. I suppose we could do some JS to check and see that a title exists and if not change the class or id but that would be a problem as you pointed out when people use the API because they could send whatever they want in one push.

**Comment by joaomgcd** [comment]
But links have their own field in the JSON. It's called "url" :) Sometimes pushes are sent with the url in both the "url" and "text" fields so that users can see what URL they are clicking.

Think of it as a notification: title is the notification title, text is the notification text and url is the stuff that opens when you click on it.

**Comment by tommyent** [comment]
So should we use the URL instead of the title? Or add some logic and add a class to text that has a URL. Right now there is no way to target the text with CSS. Also do you think the links should be orange?

**Comment by joaomgcd** [comment]
I don't think we need to worry about texts being url or titles being urls as long as the push card is clickable when it has an URL in the "url" json field :) Just present the text or title like if it were any other text or title even if it is a URL.
What do you think?

**Comment by tommyent** [comment]
Well URLs just won't stand out like the other pushes. Take a look and let me know what you think

**Comment by joaomgcd** [comment]
Awesome! :) That looks much better thank you! I've made URLs appear on pushes that only have URLs and no text because otherwise nothing would appear at all :)

Thanks again!

**Pull request merged**
