### PR TITLE
This include fix for the sms input I broke making the popup content expand. 

### PR DESCRIPTION
**Pull request by tommyent**
Definitely check on Windows. Had issues getting my machine running but it was working fine in another branch I had

### CODE REVIEW

**Comment by joaomgcd** [comment]
Unfortunately that still has some issues:

Bar is global on the right. Should be just for commands: https://drive.google.com/file/d/0B8G77eDgeMdwTUgzczd2VElTaFk/view?usp=sharing

SMS height doesn't stretch if there are just a few messages: https://drive.google.com/file/d/0B8G77eDgeMdwRkkxcV9zZGJsZ1k/view?usp=sharing

Thanks again for helping!

**Comment by joaomgcd** [comment]
SMS looks ok now, thanks!

Devices still have issues: https://drive.google.com/file/d/0B8G77eDgeMdwVndCV3dQSEVvbG8/view?usp=sharing

Buttons part is too long for the window and so you can't scroll enough to see them all. There's also a white bar on the right.

Thanks again!

**Comment by tommyent** [comment]
Sorry that was not ready. I pushed it so I could work on the windows
machine I set up. I should and since have branched it :) The next time will
be tested and ready for both Win and Mac

**Comment by joaomgcd** [comment]
No problem :) Thanks again!

**Pull request closed without merging**
