### PR TITLE
Emoji fix, SMS message fix and stylesheet fixes for consistency 

### PR DESCRIPTION
**Pull request by tommyent**

### CODE REVIEW

**Comment by tommyent** [comment]
Oh and I will make the changes to the dark stylesheet if that's the way you decide to go

**Comment by tommyent** [comment]
Never mind, Needs work I think for the options page I tried to throw in It's late I'll hit it tomorrow

**Comment by joaomgcd** [comment]
I'm currently working on a whole new structure to make everything easily themable :) Can it maybe wait until I'm done? Thanks!

**Comment by mrkevinlin** [comment]
Does it involve the global variables in CSS? Tried implementing that a while back for custom colorization, but support for global variables wasn't too great I don't think. Although it seems to be supported on browser versions from last year on all the platforms you support.

**Comment by joaomgcd** [comment]
Yeah, using global variables :) It wasn't previously available for everyone but now the latest chrome release supports it so we should be good I think!

**Pull request closed without merging**
