### PR TITLE
Change images to svg and text to icons

### PR DESCRIPTION
**Pull request by tommyent**
If you are interested this changes some of the images to svg. It also changes "Devices", "Notifications" and "SMS" wihch you may not want but you can pick out the rest. 

screen shot 2018-10-10 at 5 25 24 pm

### CODE REVIEW

**Comment by joaomgcd** [comment]
Thank you very much! :) I feel the Device, Notification and SMS tabs are a bit too small, but maybe that's just me... Don't you feel like the would need a bit more space?
Thanks again!

**Comment by tommyent** [comment]
screen shot 2018-10-11 at 7 41 51 am

**Comment by tommyent** [comment]
I also removed the style tags from the html imports 
https://bugs.chromium.org/p/chromium/issues/detail?id=523952

**Comment by joaomgcd** [comment]
Thank you very much. I know it's minor, but are you able to align the attachment and emoji icons in the SMS window? :)

**Comment by tommyent** [comment]
Sorry about that. My chrome extension is actually a branch and the fix was in there. I was actually working on this if you're interested. This moves the emaoji icon into the text area though.

For some reason when I take the screen shot it messes up the text area  
screen shot 2018-10-11 at 1 23 41 pm

**Comment by joaomgcd** [comment]
Wow that looks great :) I'd definitely want that! Is that a library?
Also, do you want to make a different pull request for that (so I can accept this one) or do you want to include it here? Thanks again!!

**Comment by tommyent** [comment]
Yeah go ahead and merge this one. This is done with emojionearea
https://github.com/mervick/emojionearea right now it functions with the
exception of I can't get it to clear the text from the input after
submitting.

**Comment by joaomgcd** [comment]
Thank you! Merged! :)

**Pull request merged**
