### PR TITLE
Remove Google + from help section

### PR DESCRIPTION
**Pull request by tommyent**

### CODE REVIEW

**Comment by tommyent** [comment]
I was thinking about making the themes more customizable with the css vars. Would you be interested in that?

**Comment by joaomgcd** [comment]
What do you mean by more customizable exactly? :)

**Comment by tommyent** [comment]
Right now we have the accent color to choose from . I was thinking something like 
Text color
Link color
Toolbar color
etc.

**Comment by joaomgcd** [comment]
Hhmm, I'm thinking those might be too many options :) No one has asked for those either so I think we're good in that department. Thanks very much for the offer anyway!!

**Pull request merged**
