### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by mrkevinlin**
Some notes:

- The notification_styles(_dark) sheets are no longer being used. They were just combined into global_styles for ease of maintenance and switching. 

- All changes to the global stylesheet currently need to be implemented on both global_styles and global_styles_dark (ie, the 100% width fix for notification images was manually added to both).

- For the device command list, the icons currently no longer also highlight orange when the button is being hovered because the JS for hovering behavior was replaced by CSS. I think there is enough visual change where this is ok for now, but it can be implemented in the future with canvas things.

- Colors can always be adjusted.

- Should be compatible with everything and should not have introduced any bugs, please let me know if there's anything bad.

Hope it goes over well

### CODE REVIEW

**Comment by tommyent** [comment]
Looks good and works good from my limited testing. 
Couple of things.
 #smsemoji is a bit too small so the left side of the face is getting cut off. Easier to see with the light theme. May just be a Mac thing but bumping it up to 22 px fixes it
https://f001.backblazeb2.com/file/DropshareNew/vF4wrJxH4B.png


Perhaps a personal thing but I'm not a fan of is the additional orange. I think using the Join orange #FF9800 looks and works better.

**Comment by joaomgcd** [comment]
Thank you very much! :D Looking great!
I think there's a problem with the popout in the devices tab though. It has a white background. It seems removing the white background on .devicecommandsleft fixes it :) Can you confirm? thanks again!

**Comment by joaomgcd** [comment]
Also, all dialogs still have a white background :) Any way to make those dark as well?

**Comment by tommyent** [comment]
I can confirm dialogs are white but I do not have the issue with the devices pop out

**Comment by joaomgcd** [comment]
Thanks Kevin! Just a question for you design experts: should the line that separates devices from commands be made lighter so you can see it with the dark theme?

**Comment by tommyent** [comment]
Personally for me I say no. Also lines seem to be removed with Android O/Material as of now.

**Comment by mrkevinlin** [comment]
Yeah, I don't think it's important. The row of circles for devices is clearly different than the vertical list of device commands, and it stays locked when scrolling so the line distinction isn't crucial.

**Comment by tommyent** [comment]
Sorry misread. I thought you were talking about the device actions. That being said I think I would lighten #devicelist background color before doing anything with the line.

**Comment by mrkevinlin** [comment]
Also to note, I think I covered everything that the dialogs might need for the dark theme, but I'm not sure I know how to trigger each type of dialog you have to check for myself. It _should_ be good, haha.

**Comment by tommyent** [comment]
From what I can tell all the dialogs that can be changed are.

Also not sure how much we are trying to follow Android but
https://material.io/guidelines/style/color.html#color-themes
following that it would look more like
https://f001.backblazeb2.com/file/DropshareNew/kwcnoRewn1.png
https://f001.backblazeb2.com/file/DropshareNew/pGhX6KuVnU.png

**Comment by joaomgcd** [comment]
Oh, sorry, I meant the dialogs like the one to write some text in an app for example :) Those kinds of popups still have light backgrounds with these changes, right? Or is it just me?

**Comment by mrkevinlin** [comment]
Strange, they should be updated.

This is what I'm seeing:
http://imgur.com/nGTCEWk

**Comment by joaomgcd** [comment]
Thanks! Can you tell me where exactly you defined the color for those so I can check my local files? thanks!

**Comment by tommyent** [comment]
@joaomgcd 
https://github.com/mrkevinlin/JoinChrome/blob/8e359854bfb0e4225b4e0751faa0aaf4373881fa/css/dialog_dark.css

**Comment by tommyent** [comment]
Sorry meant to link to 
https://github.com/joaomgcd/JoinChrome/pull/51/commits/8e359854bfb0e4225b4e0751faa0aaf4373881fa

**Comment by joaomgcd** [comment]
Ok, as you can see I changed the theming mechanism hopefully making it easier to implement and maintain. Now any themable sheet just has to have the **themesheet** attribute in its **link** html element and it will be modified with the current theme on page load.

Sounds good? :)

**Comment by mrkevinlin** [comment]
Yes! Thank you. That's kind of how I wanted to implement it in the first place but I didn't really take the time to figure it out. Fantastic.

**Comment by tommyent** [comment]
Yeah.
When you say implement does that mean custom themes going to be allowed?
If so a couple of thoughts.
Would it make sense to move themes to a themes directory? 
If custom themes will be allowed the checkboxes on the options page should be radio buttons.
Would it make sense to have a json file for the themes. e.g. theme name, machine name, author, url etc. This would allow for theme authors to be responsible for debugging and not fall on @joaomgcd

**Comment by tommyent** [comment]
So I think I mentioned this awhile back but my idea was to load another style sheet. I fee this is a better idea than what's currently in place due to the fact that you now have to maintain multiple copies of the style sheets. The same thing that's being done with the Materialize css.

If community themes are going to be accepted then it would be theme-name.css or something loading last. If there was not an official themes directory in the repo it would be nice to call a user.css from somewhere. Not sure if you could do a Join directory and not have it get deleted on update but Drive, server, Gist, Github, etc. My dark theme I was using was like 30-50 lines of css so really they could probably be stored in localStorage, handled like the App Websites in settings and injected into the page.

The only thing I see worth maintaining two of would be the html files. Something like a wide (Hangouts style) and narrow (current Join). Then themes would be nothing more than css overrides. 

The user sheets definitely seem to be  something worthwhile from reading comments like the following from just the last post. 

> ... Can we have option for not have orange
>... maybe even black :)

**Comment by joaomgcd** [comment]
I'm going it to make it all changeable dynamically so users can choose whatever colors they want from a UI without having to implement their own CSS :) I'm working on it now!

**Comment by joaomgcd** [comment]
Let me know how you like the new theming stuff. My plan was to add a "custom" theme in the future (besides some pre-made ones) where the person can pick their colors individually with a color picker. That's already possible with the framework I implemented, just a matter of creating a UI for it :)
Will have to do that later!
I have now also included a green theme to give an example of another theme.

**Comment by mrkevinlin** [comment]
Hi, I definitely like how robust it can be. There are a bunch of small things that have changed, interestingly.

**Overall things**
1. The ripple animation for the main tabs at the top have changed to be strangely white on the borders when navigating to it. Clicking the current tab again does the expected ripple behavior from before.
2. The dialog buttons only change text color and drop shadow when hovered. It would look better if the button also turned a lighter color.
3. The title message of dialogs are still join orange, unsure if that is intended behavior.
**Notifications**
1. The action buttons on notifications currently turn to join orange text when hovered, not sure if that is intended behavior.
2. The clear all FAB has lost its transition
3. The x to close notifications is still black on the dark background themes, making it hard to see.
**SMS related**
1. The hover transition for the + FAB seems to have been lost. It is an instantaneous color change.
2. The call icon for each SMS thread is back to a dark gray in the themes with dark backgrounds, making it hard to see.
3. The attachment button is not currently working.
4. I'd like a margin to the right of the attachment button of 6px to separate it a bit from the emoji button.
The attachment button animates to the hover color but the send button does not.
5. The <- Name back button in SMS conversations does not have a transition because box shadow is not animated for some reason. Setting background-color does make it transition.
6. Remove the #smstitle:hover { max-height:none;} attribute because it makes the <- Name back button gain strange height when hovered.
**Options**
1. The action buttons in each option section currently have black text on darker colored backgrounds no matter what theme; I think a white font would look nicer.
2. The action buttons as well as the tabs in options turn the same color as text when hovered (particularly in the dark themes), making it impossible to read.

Sorry for a huge list of nitpicks. I don't currently have the time to fix them at the moment, but those are the bits of polish that we've lost!

**Comment by mrkevinlin** [comment]
A while back I actually was working on custom themes, but I hit a bit of a snag and temporarily abandoned it. I don't remember if I've shared the idea yet, but I'll repost it anyway!

HTML actually provides a default color picker thing. It's not very pretty but it's built in!
http://imgur.com/a/LlWub

There would be one global color that the user entered, and based on that one main color theme, the other matching colors would be automatically generated. 

At first, my initial idea was the whole theme would just be variants of that chosen color. For example, choosing purple would result in dark purple tab bar, light purple notification cards, purple purple purple variants etc. I also intended to calculate based on Google's accessibility guidelines whether to make the text white or black for maximum legibility based on the generated color it would be sitting on, but that got ugly really fast.

But the new idea that would be better would be simply the user choosing the main accent color and then choosing whether or not to have a light color or dark color theme. The custom color would just color buttons and the like. Saves a lot of complication. Not sure how you'd like to proceed, but I think programmatically generating themes that way is pretty nifty, haha.

**Comment by joaomgcd** [comment]
Sorry for the long delay! Finally have time to look at this again!

Yeah, that does sound like a good idea! :) Let the person choose the accent color and then switch between pre-defined light and dark themes! 

Good thinking!

I'll try fixing the issues you mentioned above, thanks!

**Comment by joaomgcd** [comment]
Ok, I made the changes now :) Let me know how they work for you if you can!

**Comment by tommyent** [comment]
Works

**Pull request merged**
